-- НОВЫЕ ГРАНИ: схема Supabase для полноценного режима
-- Выполните этот файл целиком в Supabase Dashboard → SQL Editor.

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.site_content (
  id bigint primary key,
  content jsonb not null,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);

create table if not exists public.site_events (
  id bigint generated by default as identity primary key,
  event_name text not null check (event_name in ('pageview','vk_click','photo_open','faq_open','album_order')),
  album_id text check (album_id is null or length(album_id) <= 80),
  path text check (path is null or length(path) <= 500),
  referrer text check (referrer is null or length(referrer) <= 1000),
  created_at timestamptz not null default now()
);

create or replace function public.is_site_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_users where user_id = auth.uid()
  );
$$;

create or replace function public.set_site_content_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  new.updated_by = auth.uid();
  return new;
end;
$$;

drop trigger if exists site_content_set_updated_at on public.site_content;
create trigger site_content_set_updated_at
before insert or update on public.site_content
for each row execute function public.set_site_content_updated_at();

alter table public.admin_users enable row level security;
alter table public.site_content enable row level security;
alter table public.site_events enable row level security;

-- Повторный запуск файла безопасен: старые политики удаляются и создаются заново.
drop policy if exists "admin reads own membership" on public.admin_users;
create policy "admin reads own membership"
on public.admin_users for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "public reads site content" on public.site_content;
create policy "public reads site content"
on public.site_content for select
to anon, authenticated
using (true);

drop policy if exists "admins insert site content" on public.site_content;
create policy "admins insert site content"
on public.site_content for insert
to authenticated
with check (public.is_site_admin());

drop policy if exists "admins update site content" on public.site_content;
create policy "admins update site content"
on public.site_content for update
to authenticated
using (public.is_site_admin())
with check (public.is_site_admin());

drop policy if exists "visitors insert analytics events" on public.site_events;
create policy "visitors insert analytics events"
on public.site_events for insert
to anon, authenticated
with check (
  event_name in ('pageview','vk_click','photo_open','faq_open','album_order')
  and (album_id is null or length(album_id) <= 80)
  and (path is null or length(path) <= 500)
  and (referrer is null or length(referrer) <= 1000)
);

drop policy if exists "admins read analytics events" on public.site_events;
create policy "admins read analytics events"
on public.site_events for select
to authenticated
using (public.is_site_admin());

drop policy if exists "admins delete analytics events" on public.site_events;
create policy "admins delete analytics events"
on public.site_events for delete
to authenticated
using (public.is_site_admin());

grant select on public.admin_users to authenticated;
grant select on public.site_content to anon, authenticated;
grant insert, update on public.site_content to authenticated;
grant insert on public.site_events to anon, authenticated;
grant select, delete on public.site_events to authenticated;
grant usage, select on sequence public.site_events_id_seq to anon, authenticated;
grant execute on function public.is_site_admin() to anon, authenticated;

create or replace function public.get_site_stats()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  result jsonb;
begin
  if not public.is_site_admin() then
    raise exception 'Forbidden';
  end if;

  select jsonb_build_object(
    'pageviews', count(*) filter (where event_name = 'pageview'),
    'events_total', count(*),
    'vk_click', count(*) filter (where event_name = 'vk_click'),
    'photo_open', count(*) filter (where event_name = 'photo_open'),
    'faq_open', count(*) filter (where event_name = 'faq_open'),
    'album_order', count(*) filter (where event_name = 'album_order'),
    'by_event', coalesce((
      select jsonb_object_agg(event_name, total)
      from (
        select event_name, count(*) as total
        from public.site_events
        group by event_name
      ) grouped
    ), '{}'::jsonb)
  ) into result
  from public.site_events;

  return result;
end;
$$;

revoke all on function public.get_site_stats() from public;
grant execute on function public.get_site_stats() to authenticated;

-- Публичное хранилище фотографий. Загружать и удалять может только администратор.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'site-images',
  'site-images',
  true,
  10485760,
  array['image/jpeg','image/png','image/webp','image/avif','image/gif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "public reads site images" on storage.objects;
create policy "public reads site images"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'site-images');

drop policy if exists "admins upload site images" on storage.objects;
create policy "admins upload site images"
on storage.objects for insert
to authenticated
with check (bucket_id = 'site-images' and public.is_site_admin());

drop policy if exists "admins update site images" on storage.objects;
create policy "admins update site images"
on storage.objects for update
to authenticated
using (bucket_id = 'site-images' and public.is_site_admin())
with check (bucket_id = 'site-images' and public.is_site_admin());

drop policy if exists "admins delete site images" on storage.objects;
create policy "admins delete site images"
on storage.objects for delete
to authenticated
using (bucket_id = 'site-images' and public.is_site_admin());

insert into public.site_content (id, content)
values (1, $content$
{
  "brand": {
    "name": "НОВЫЕ ГРАНИ",
    "tagline": "Школьные фотокниги, которые хочется пересматривать",
    "vk": "https://vk.com/nsk_photobook",
    "phone": "",
    "city": "Новосибирск"
  },
  "hero": {
    "eyebrow": "Премиальная школьная фотография",
    "title": "История класса — в книге, которая останется навсегда",
    "text": "Создаём современные школьные альбомы: от продуманной съёмки до дизайнерской верстки и качественной печати.",
    "image": "assets/images/demo-01.svg"
  },
  "albums": [
    {
      "id": "classic",
      "name": "CLASSIC",
      "price": "3 900 ₽",
      "badge": "Базовый",
      "lead": "Лаконичный выпускной альбом с индивидуальным портретом и фотографиями класса.",
      "details": [
        "1 съёмочный день",
        "6 разворотов",
        "Твёрдая обложка",
        "Персональная обложка",
        "Срок — до 45 дней"
      ],
      "cover": "assets/images/demo-02.svg",
      "gallery": [
        "assets/images/demo-02.svg",
        "assets/images/demo-03.svg",
        "assets/images/demo-04.svg"
      ]
    },
    {
      "id": "story",
      "name": "STORY",
      "price": "5 900 ₽",
      "badge": "Самый популярный",
      "lead": "Живой репортаж, индивидуальные портреты и история класса в журнальной подаче.",
      "details": [
        "2 съёмочных дня",
        "10 разворотов",
        "Премиальная фотобумага",
        "Индивидуальный дизайн",
        "Срок — до 55 дней"
      ],
      "cover": "assets/images/demo-05.svg",
      "gallery": [
        "assets/images/demo-05.svg",
        "assets/images/demo-06.svg",
        "assets/images/demo-07.svg"
      ]
    },
    {
      "id": "signature",
      "name": "SIGNATURE",
      "price": "8 900 ₽",
      "badge": "Премиум",
      "lead": "Авторский альбом с расширенной съёмкой, сложной версткой и максимальной персонализацией.",
      "details": [
        "3 съёмочных дня",
        "16 разворотов",
        "Дизайнерская обложка",
        "Расширенная ретушь",
        "Срок — до 65 дней"
      ],
      "cover": "assets/images/demo-08.svg",
      "gallery": [
        "assets/images/demo-08.svg",
        "assets/images/demo-09.svg",
        "assets/images/demo-10.svg"
      ]
    }
  ],
  "process": [
    {
      "title": "Знакомство",
      "text": "Обсуждаем класс, формат альбома, сроки и пожелания родителей."
    },
    {
      "title": "Подготовка",
      "text": "Помогаем выбрать образы, согласовываем локации и сценарий съёмки."
    },
    {
      "title": "Фотосъёмка",
      "text": "Снимаем индивидуальные портреты, друзей, учителей и живые школьные моменты."
    },
    {
      "title": "Дизайн",
      "text": "Отбираем кадры, выполняем ретушь и создаём персональный макет."
    },
    {
      "title": "Согласование",
      "text": "Перед печатью проверяем имена, тексты и состав фотографий."
    },
    {
      "title": "Готовые альбомы",
      "text": "Печатаем, проверяем каждый экземпляр и передаём классу."
    }
  ],
  "faq": [
    {
      "q": "Как подготовиться к фотосъёмке?",
      "a": "За 7–10 дней вы получите памятку с рекомендациями по одежде, причёске и подготовке класса."
    },
    {
      "q": "Что делать, если ребёнок заболел?",
      "a": "Для пропустивших основную съёмку заранее предусматривается резервная дата или индивидуальная досъёмка."
    },
    {
      "q": "Можно ли выбрать фотографии?",
      "a": "Да. В зависимости от тарифа родители выбирают основной портрет, а ключевые развороты проходят согласование."
    },
    {
      "q": "Можно ли заказать дополнительный экземпляр?",
      "a": "Да, дополнительный альбом можно заказать до передачи макета в печать."
    },
    {
      "q": "Когда оплачивается заказ?",
      "a": "Тестовая схема: 30% после бронирования даты, остаток — после утверждения макета."
    },
    {
      "q": "Сколько длится фотосъёмка?",
      "a": "Обычно от 3 до 6 часов в зависимости от выбранного альбома и количества учеников."
    }
  ],
  "reviews": [
    {
      "name": "Елена, родитель 9 класса",
      "text": "Очень современный альбом. Дети выглядят естественно, а вся книга ощущается как настоящий журнал."
    },
    {
      "name": "Марина Викторовна, классный руководитель",
      "text": "Организация была спокойной и понятной: график, памятки, согласование — всё без лишней нагрузки на школу."
    },
    {
      "name": "Ольга, родитель 11 класса",
      "text": "Особенно понравилось, что у каждого ребёнка получилась своя история, а не просто одинаковые портреты."
    }
  ]
}
$content$::jsonb)
on conflict (id) do nothing;

-- ПОСЛЕ создания пользователя в Authentication → Users выполните отдельно:
-- insert into public.admin_users(user_id) values ('UUID_ПОЛЬЗОВАТЕЛЯ');
