(() => {
  const cfg=window.SITE_CONFIG||{}, defaults=window.DEFAULT_SITE_CONTENT;
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  let client=null,data=structuredClone(defaults),saved=structuredClone(defaults),currentTab='overview',session=null;
  const configured=()=>cfg.SUPABASE_URL&&!cfg.SUPABASE_URL.includes('YOUR_PROJECT')&&cfg.SUPABASE_PUBLISHABLE_KEY&&!cfg.SUPABASE_PUBLISHABLE_KEY.includes('YOUR_');
  const clone=x=>structuredClone(x);
  const deepMerge=(base,extra)=>{if(Array.isArray(base)) return Array.isArray(extra)?extra:base;if(base&&typeof base==='object'){const out={...base};if(extra&&typeof extra==='object')Object.keys(extra).forEach(k=>out[k]=k in base?deepMerge(base[k],extra[k]):extra[k]);return out}return extra??base};
  const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  function migrate(raw){const x=clone(raw||{});if(Array.isArray(x.portfolio)){x.portfolio={...defaults.portfolio,items:x.portfolio}}if(x.portfolioSection){x.portfolio={...(x.portfolio||{}),...x.portfolioSection}}if(x.portfolio?.circleText&&!x.portfolio.circle)x.portfolio.circle={...defaults.portfolio.circle,outerText:x.portfolio.circleText};return deepMerge(defaults,x)}
  function get(path){return path.split('.').reduce((o,k)=>o?.[k],data)}
  function set(path,value){const keys=path.split('.');let o=data;for(let i=0;i<keys.length-1;i++){const k=keys[i],next=keys[i+1];if(o[k]==null)o[k]=/^\d+$/.test(next)?[]:{};o=o[k]}o[keys[keys.length-1]]=value}
  const field=(label,path,value,opts={})=>`<label class="${opts.full?'full':''}">${esc(label)}${opts.textarea?`<textarea data-path="${path}">${esc(value)}</textarea>`:`<input data-path="${path}" type="${opts.type||'text'}" value="${esc(value)}" ${opts.min!=null?`min="${opts.min}"`:''} ${opts.max!=null?`max="${opts.max}"`:''} ${opts.step!=null?`step="${opts.step}"`:''}>`}</label>`;
  const checkbox=(label,path,value)=>`<label><span>${esc(label)}</span><input data-path="${path}" type="checkbox" ${value?'checked':''}></label>`;
  const color=(label,path,value)=>`<label>${esc(label)}<span class="color-field"><input data-path="${path}" type="color" value="${esc(value)}"><input data-path="${path}" type="text" value="${esc(value)}"></span></label>`;
  const upload=(label,path,value)=>`<div class="full"><label>${esc(label)}</label><div class="upload-row"><input data-path="${path}" value="${esc(value||'')}" placeholder="URL изображения"><button type="button" class="secondary upload-button" data-upload="${path}">Загрузить</button></div>${value?`<img class="preview-img" src="${esc(value)}" alt="Предпросмотр">`:''}</div>`;
  async function init(){if(configured()&&window.supabase){client=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY);const {data:{session:s}}=await client.auth.getSession();if(s){session=s;await enter()}else showLogin()}else{showLogin(true)}}
  function showLogin(local=false){$('#loginScreen').hidden=false;$('#adminApp').hidden=true;if(local)$('#loginMessage').textContent='Демо-режим: email любой, пароль admin2026. Для общей базы заполните config.js.'}
  $('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const email=$('#loginEmail').value.trim(),password=$('#loginPassword').value;if(client){$('#loginMessage').textContent='Выполняется вход…';const {data:d,error}=await client.auth.signInWithPassword({email,password});if(error){$('#loginMessage').textContent=error.message;return}session=d.session;await enter()}else{if(password!=='admin2026'){$('#loginMessage').textContent='Неверный демо-пароль';return}session={user:{email}};await enter()}});
  async function enter(){try{if(client){const {data:membership}=await client.from('admin_users').select('user_id').eq('user_id',session.user.id).maybeSingle();if(!membership)throw new Error('Пользователь вошёл, но его UID не добавлен в public.admin_users');const {data:row,error}=await client.from('site_content').select('content').eq('id',cfg.CONTENT_ROW_ID||1).maybeSingle();if(error)throw error;data=migrate(row?.content||defaults)}else{data=migrate(JSON.parse(localStorage.getItem('schoolPhotoContent')||'null')||defaults)}saved=clone(data);$('#loginScreen').hidden=true;$('#adminApp').hidden=false;render()}catch(e){$('#loginMessage').textContent=e.message;$('#loginScreen').hidden=false;$('#adminApp').hidden=true}}
  $('#logoutButton').addEventListener('click',async()=>{if(client)await client.auth.signOut();location.reload()});
  $('#adminNav').addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(!b)return;currentTab=b.dataset.tab;$$('#adminNav button').forEach(x=>x.classList.toggle('active',x===b));render()});
  $('#resetButton').addEventListener('click',()=>{data=clone(saved);render();status('Форма возвращена к последнему сохранению')});
  $('#saveButton').addEventListener('click',save);
  function status(t,err=false){const n=$('#saveStatus');n.textContent=t;n.style.color=err?'#a33':''}
  async function save(){status('Сохранение…');try{if(client){const {error}=await client.from('site_content').upsert({id:cfg.CONTENT_ROW_ID||1,content:data},{onConflict:'id'});if(error)throw error}else localStorage.setItem('schoolPhotoContent',JSON.stringify(data));saved=clone(data);status('Сохранено')}catch(e){status(e.message,true)}}
  function bind(){
    $$('[data-path]').forEach(n=>{const handler=()=>{let v=n.type==='checkbox'?n.checked:n.value;if(n.type==='number')v=Number(v);set(n.dataset.path,v);status('Есть несохранённые изменения');if(n.dataset.path.startsWith('portfolio.circle.'))refreshCirclePreview();if(n.type==='color')$$(`[data-path="${CSS.escape(n.dataset.path)}"]`).forEach(x=>{if(x!==n)x.value=v})};n.addEventListener('input',handler);n.addEventListener('change',handler)});
    $$('.upload-button').forEach(b=>b.addEventListener('click',()=>chooseFile(b.dataset.upload)));
    $$('[data-delete]').forEach(b=>b.addEventListener('click',()=>{const [arr,i]=b.dataset.delete.split('|');get(arr).splice(+i,1);render();status('Элемент удалён; сохраните изменения')}));
    $$('[data-add]').forEach(b=>b.addEventListener('click',()=>{const arr=get(b.dataset.add);if(b.dataset.add==='portfolio.items')arr.push({image:'',full:'',label:'Новая фотография',alt:'Фотография из портфолио'});if(b.dataset.add==='process')arr.push({number:String(arr.length+1).padStart(2,'0'),title:'Новый этап',text:'Описание этапа'});if(b.dataset.add==='faq')arr.push({question:'Новый вопрос',answer:'Ответ'});render();status('Элемент добавлен; сохраните изменения')}));
  }
  async function chooseFile(path){const input=document.createElement('input');input.type='file';input.accept='image/jpeg,image/png,image/webp,image/avif,image/gif,image/svg+xml';input.onchange=async()=>{const file=input.files[0];if(!file)return;status('Загрузка изображения…');try{let url;if(client){const safe=file.name.toLowerCase().replace(/[^a-z0-9._-]/g,'-');const object=`uploads/${Date.now()}-${safe}`;const {error}=await client.storage.from(cfg.STORAGE_BUCKET||'site-images').upload(object,file,{upsert:false});if(error)throw error;url=client.storage.from(cfg.STORAGE_BUCKET||'site-images').getPublicUrl(object).data.publicUrl}else url=await new Promise((res,rej)=>{const r=new FileReader;r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)});set(path,url);if(path.match(/^portfolio\.items\.\d+\.image$/))set(path.replace(/\.image$/,'.full'),url);render();status('Изображение загружено; нажмите «Сохранить»')}catch(e){status(e.message,true)}};input.click()}
  function render(){const titles={overview:'Обзор',general:'Основное и логотипы',albums:'Альбомы',portfolio:'Портфолио и текст в круге',process:'Этапы съёмки',faq:'Частые вопросы',design:'Дизайн и шрифты'};$('#pageTitle').textContent=titles[currentTab];const fn={overview:renderOverview,general:renderGeneral,albums:renderAlbums,portfolio:renderPortfolio,process:renderProcess,faq:renderFaq,design:renderDesign}[currentTab];$('#workspace').innerHTML=fn();bind();if(currentTab==='overview')loadStats();if(currentTab==='portfolio')refreshCirclePreview()}
  function renderOverview(){return `<div class="stats"><div class="stat"><b id="sPage">—</b><span>Просмотры</span></div><div class="stat"><b id="sVk">—</b><span>Переходы VK</span></div><div class="stat"><b id="sPhoto">—</b><span>Открытия фото</span></div><div class="stat"><b id="sOrder">—</b><span>Заказы</span></div></div><section class="panel"><h2>Состояние сайта</h2><p>Версия контента: ${esc(data.version||3)}. Публичная ссылка на административную панель отсутствует. Для входа используйте прямой адрес <code>/admin/</code>.</p><p class="panel-note">Исправленная версия позволяет редактировать весь заголовочный текст портфолио, подписи изображений и четыре текстовых поля круглого элемента.</p></section>`}
  async function loadStats(){if(!client){['sPage','sVk','sPhoto','sOrder'].forEach(id=>$('#'+id).textContent='0');return}const {data:s}=await client.rpc('get_site_stats');if(!s)return;$('#sPage').textContent=s.pageviews||0;$('#sVk').textContent=s.vk_click||0;$('#sPhoto').textContent=s.photo_open||0;$('#sOrder').textContent=s.album_order||0}
  function renderGeneral(){return `<section class="panel"><h2>Название и контакты</h2><div class="form-grid">${field('Название студии','site.name',data.site.name)}${field('Подпись бренда','site.tagline',data.site.tagline)}${field('Ссылка VK','site.vkUrl',data.site.vkUrl,{full:true})}${field('Текст кнопки в шапке','site.headerButton',data.site.headerButton)}${field('Текст подвала','site.footerText',data.site.footerText,{textarea:true,full:true})}</div></section><section class="panel"><h2>Логотипы</h2><div class="form-grid">${field('Буквенный знак','logos.markText',data.logos.markText)}${checkbox('Показывать название','logos.showName',data.logos.showName)}${checkbox('Показывать подпись','logos.showTagline',data.logos.showTagline)}${upload('Логотип шапки','logos.headerUrl',data.logos.headerUrl)}${upload('Логотип подвала','logos.footerUrl',data.logos.footerUrl)}${upload('Favicon','logos.faviconUrl',data.logos.faviconUrl)}</div></section><section class="panel"><h2>Первый экран</h2><div class="form-grid">${field('Надзаголовок','hero.eyebrow',data.hero.eyebrow,{full:true})}${field('Основная строка','hero.title',data.hero.title)}${field('Акцентная строка','hero.accent',data.hero.accent)}${field('Описание','hero.text',data.hero.text,{textarea:true,full:true})}${field('Кнопка','hero.button',data.hero.button)}${field('Нижняя подпись','hero.note',data.hero.note)}${upload('Главная фотография','hero.image',data.hero.image)}</div></section>`}
  function renderAlbums(){return `<section class="panel"><h2>Заголовок раздела</h2><div class="form-grid">${field('Надзаголовок','albumsSection.eyebrow',data.albumsSection.eyebrow)}${field('Заголовок','albumsSection.title',data.albumsSection.title)}${field('Описание','albumsSection.text',data.albumsSection.text,{textarea:true,full:true})}</div></section>${data.albums.map((a,i)=>`<section class="panel"><h2>${esc(a.name)}</h2><div class="form-grid">${field('Название',`albums.${i}.name`,a.name)}${field('Подзаголовок',`albums.${i}.subtitle`,a.subtitle)}${field('Цена',`albums.${i}.price`,a.price)}${field('Метка',`albums.${i}.badge`,a.badge)}${field('Описание',`albums.${i}.description`,a.description,{textarea:true,full:true})}${field('Характеристики — по одной на строку',`albums.${i}.detailsText`,a.details.join('\n'),{textarea:true,full:true})}${field('Текст кнопки',`albums.${i}.button`,a.button)}${upload('Изображение',`albums.${i}.image`,a.image)}</div></section>`).join('')}`}
  function renderPortfolio(){const p=data.portfolio;return `<section class="panel"><h2>Текст раздела «Портфолио»</h2><p class="panel-note">Теперь эти поля напрямую управляют надзаголовком, двумя строками заголовка, описанием и подсказкой под галереей.</p><div class="form-grid">${field('Надзаголовок','portfolio.eyebrow',p.eyebrow)}${field('Первая строка заголовка','portfolio.title',p.title)}${field('Акцентная строка заголовка','portfolio.accent',p.accent)}${field('Описание портфолио','portfolio.description',p.description,{textarea:true,full:true})}${field('Подсказка под галереей','portfolio.swipeHint',p.swipeHint,{full:true})}</div></section><section class="panel"><h2>Текст в круглом элементе</h2><p class="panel-note">Исправлено: каждая надпись в круге редактируется отдельно. Внешний текст автоматически размещается по окружности.</p><div class="form-grid"><div>${field('Текст по окружности','portfolio.circle.outerText',p.circle.outerText,{textarea:true,full:true})}${field('Верхняя строка внутри круга','portfolio.circle.centerTop',p.circle.centerTop)}${field('Крупная центральная строка','portfolio.circle.centerMain',p.circle.centerMain)}${field('Нижняя строка внутри круга','portfolio.circle.centerBottom',p.circle.centerBottom)}</div><div><div id="circlePreview" class="circle-preview"><svg viewBox="0 0 220 220" aria-hidden="true"><defs><path id="adminCirclePath" d="M110,110 m-84,0 a84,84 0 1,1 168,0 a84,84 0 1,1 -168,0"/></defs><circle cx="110" cy="110" r="102"/><text><textPath id="cpOuterPath" href="#adminCirclePath"></textPath></text></svg><div class="circle-preview-center"><span id="cpTop"></span><strong id="cpMain"></strong><span id="cpBottom"></span></div></div></div></div></section><section class="panel"><div class="item-head"><div><h2>Фотографии и подписи</h2><p class="panel-note">Можно изменить подпись на карточке, описание для доступности и само изображение.</p></div><button type="button" data-add="portfolio.items">Добавить фото</button></div>${p.items.map((x,i)=>`<article class="item-card"><div class="item-head"><h3>Фотография ${i+1}</h3><button type="button" class="danger" data-delete="portfolio.items|${i}">Удалить</button></div><div class="form-grid">${field('Подпись на фотографии',`portfolio.items.${i}.label`,x.label)}${field('Описание изображения (alt)',`portfolio.items.${i}.alt`,x.alt)}${upload('Изображение',`portfolio.items.${i}.image`,x.image)}${field('Полноразмерное изображение — URL',`portfolio.items.${i}.full`,x.full,{full:true})}</div></article>`).join('')}</section>`}
  function refreshCirclePreview(){if(!$('#circlePreview'))return;setText('#cpOuterPath',get('portfolio.circle.outerText'));setText('#cpTop',get('portfolio.circle.centerTop'));setText('#cpMain',get('portfolio.circle.centerMain'));setText('#cpBottom',get('portfolio.circle.centerBottom'))}
  function setText(sel,val){const n=$(sel);if(n)n.textContent=val||''}
  function renderProcess(){return `<section class="panel"><h2>Заголовок раздела</h2><div class="form-grid">${field('Надзаголовок','processSection.eyebrow',data.processSection.eyebrow)}${field('Первая строка','processSection.title',data.processSection.title)}${field('Акцентная строка','processSection.accent',data.processSection.accent)}${field('Описание','processSection.text',data.processSection.text,{textarea:true,full:true})}</div></section><section class="panel"><div class="item-head"><h2>Этапы</h2><button data-add="process">Добавить этап</button></div>${data.process.map((x,i)=>`<article class="item-card"><div class="item-head"><h3>Этап ${i+1}</h3><button class="danger" data-delete="process|${i}">Удалить</button></div><div class="form-grid">${field('Номер',`process.${i}.number`,x.number)}${field('Заголовок',`process.${i}.title`,x.title)}${field('Описание',`process.${i}.text`,x.text,{textarea:true,full:true})}</div></article>`).join('')}</section>`}
  function renderFaq(){return `<section class="panel"><h2>Заголовок раздела</h2><div class="form-grid">${field('Надзаголовок','faqSection.eyebrow',data.faqSection.eyebrow)}${field('Заголовок','faqSection.title',data.faqSection.title)}${field('Описание','faqSection.text',data.faqSection.text,{textarea:true,full:true})}</div></section><section class="panel"><div class="item-head"><h2>Вопросы</h2><button data-add="faq">Добавить вопрос</button></div>${data.faq.map((x,i)=>`<article class="item-card"><div class="item-head"><h3>Вопрос ${i+1}</h3><button class="danger" data-delete="faq|${i}">Удалить</button></div><div class="form-grid">${field('Вопрос',`faq.${i}.question`,x.question,{full:true})}${field('Ответ',`faq.${i}.answer`,x.answer,{textarea:true,full:true})}</div></article>`).join('')}</section>`}
  function renderDesign(){const d=data.design;return `<section class="panel"><h2>Шрифты</h2><div class="form-grid">${field('Основной шрифт','design.fonts.bodyFamily',d.fonts.bodyFamily)}${field('Шрифт заголовков','design.fonts.headingFamily',d.fonts.headingFamily)}${field('Шрифт меню','design.fonts.menuFamily',d.fonts.menuFamily)}${field('Шрифт кнопок','design.fonts.buttonFamily',d.fonts.buttonFamily)}${field('Шрифт бренда','design.fonts.brandFamily',d.fonts.brandFamily)}${field('CSS-ссылка внешнего шрифта','design.fonts.stylesheetUrl',d.fonts.stylesheetUrl,{full:true})}</div></section><section class="panel"><h2>Цвета</h2><div class="form-grid three">${Object.entries({background:'Фон',surface:'Карточки',text:'Текст',muted:'Вторичный текст',accent:'Акцент',accent2:'Дополнительный акцент',border:'Границы',dark:'Тёмный фон',darkText:'Текст на тёмном фоне',circle:'Круг'}).map(([k,l])=>color(l,`design.colors.${k}`,d.colors[k])).join('')}</div></section><section class="panel"><h2>Размеры текста</h2><div class="form-grid three">${Object.entries({bodySize:'Основной текст',menuSize:'Меню',buttonSize:'Кнопки',heroTitleSize:'Главный заголовок',sectionTitleSize:'Заголовки разделов',cardTitleSize:'Названия альбомов',cardTextSize:'Текст карточек',priceSize:'Цена',eyebrowSize:'Надзаголовки',faqSize:'Вопросы FAQ',brandNameSize:'Название бренда',brandTaglineSize:'Подпись бренда',portfolioLabelSize:'Подписи фото',circleOuterSize:'Текст по кругу',circleTopSize:'Верх внутри круга',circleMainSize:'Центр круга',circleBottomSize:'Низ внутри круга'}).map(([k,l])=>field(`${l}, px`,`design.typography.${k}`,d.typography[k],{type:'number',min:7,max:140})).join('')}${field('Межстрочный интервал','design.typography.bodyLineHeight',d.typography.bodyLineHeight,{type:'number',min:.8,max:3,step:.05})}${field('Толщина заголовков','design.typography.headingWeight',d.typography.headingWeight,{type:'number',min:100,max:900,step:100})}${field('Толщина текста','design.typography.bodyWeight',d.typography.bodyWeight,{type:'number',min:100,max:900,step:100})}${field('Межбуквенный интервал, px','design.typography.letterSpacing',d.typography.letterSpacing,{type:'number',min:-3,max:12,step:.1})}</div></section><section class="panel"><h2>Размеры и скругления</h2><div class="form-grid three">${Object.entries({contentWidth:'Ширина контента',sidePadding:'Боковые поля',sectionGap:'Отступ разделов',cardRadius:'Скругление карточек',imageRadius:'Скругление изображений',buttonRadius:'Скругление кнопок',headerHeight:'Высота шапки',circleSize:'Размер круга'}).map(([k,l])=>field(`${l}, px`,`design.layout.${k}`,d.layout[k],{type:'number',min:0,max:1600})).join('')}</div></section>`}
  // detailsText is a virtual editing field converted back into details on save/input
  document.addEventListener('input',e=>{if(e.target.dataset?.path?.endsWith('.detailsText')){const p=e.target.dataset.path.replace(/\.detailsText$/,'.details');set(p,e.target.value.split('\n').map(x=>x.trim()).filter(Boolean))}},true);
  init();
})();
